version: "3.3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: hoopless-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxynet

  webserver:
    environment:
      - VIRTUAL_HOST=localhost
    networks:
      - proxynet

  mysql:
    build:
      context: ./
      dockerfile: /docker/mysql/Dockerfile
    container_name: hoopless-mysql
    working_dir: /application
    volumes:
      - ./app/sql:/docker-entrypoint-initdb.d:rw
    ports:
      - "3306:3306"
    env_file:
      - ./docker/env/dev.env
    networks:
      - proxynet

  php-fpm:
    build:
      target: standard
    networks:
      - proxynet

networks:
  proxynet:
    external: false
