version: "3.8"
services:

    mysql:
      image: mysql:8.0
      container_name: hoopless-mysql
      working_dir: /application
      volumes:
        - ./app:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root_user_pwd
        - MYSQL_DATABASE=hoopless
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app_pwd
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: hoopless-webserver
      working_dir: /application
      volumes:
          - ./app:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"

    php-fpm:
      build: ./docker/php-fpm
      container_name: hoopless-php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
