version: "3.4"

services:

  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - proxynet

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ocms-letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=admin@ouxsoft.com
      - NGINX_PROXY_CONTAINER=ocms-nginx-proxy

  webserver:
    environment:
      - VIRTUAL_HOST=ouxsoft.com
      - LETSENCRYPT_HOST=ouxsoft.com
    expose:
      - 80
    restart: unless-stopped
    networks:
      - proxynet

  php-fpm:
    build:
      target: standard
    restart: unless-stopped
    networks:
      - proxynet
    depends_on:
      - mysql

  mysql:
    container_name: ocms-mysql
    image: mysql:8.0
    command: --init-file /docker-entrypoint-initdb.d/01-init.sql
    volumes:
      # copy and rename to ensure execute in lexicographical (sorted, alphabetical) order
      - ./sql/hoopless.sql:/docker-entrypoint-initdb.d/01-init.sql
      # store database inside volume mount
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=hoopless
    networks:
      - proxynet
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5

networks:
  proxynet:
    external: false

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
  dbdata: