<?php
echo "<div class=\"container background-white\">";

echo '<h2>Problem</h2>';
echo '<p>As a result of manufacturing processes, all the metal parts were casted with a non-metal layer on top that needed to be removed in order for the metal in the part to show. The parts would need to be buffed and polished from one end of the part to the other end evenly to remove this outer layer. Operators would use FANUC&reg; robots to buff and polish parts evenly. The OEM programmed the robots to work by using multiple programs, which each contained static positions that the robot would use to process the parts. Although this good in theory, due to environmental variables, this resulted in poor quality parts, unnecessary downtime, high operator knowledge requirements, potentially harmful situation, and costly scrap.</p>';
echo '<p>To setup for a part first an operator would have to load a program for that part from the computer to the robotic controller, which took several minutes. Secondly, the operator would have to manually adjust the x, y, and z coordinates for each of the program\'s position based on the current environmental conditions (buff and polish wheel dimensions and compound cake, part thickness, etc.). This process was time consuming; often it would take up to an hour for each type of part to be setup. This process was also hazardous; if the operator mistakenly typed a wrong coordinate as the often did then the robot, the workcell, the jigs, the parts, and the operator could be harmed.</p>';
echo '<h2>Solution</h2>';
echo '<p>I knew if all the variables were processed in a set of effective procedures a single program could be made that processed all the parts currently manufactured and that were likely to be manufactured in the future perfectly. Even though the operators did not believe a single program could be used to process the thousands of varying parts the manufactured made, I started with pen and paper defining all the requirements of the program on the large scale, e.g. operator requirements, production requirements, etc. Next, I defined the algorithms that would be used to calculate each potential position. Third, I wrote the entire program as pseudo code. Then I programmed the computer, robotic controller, and interface using the pseudo code.</p>';
echo '<p>I had some hurdles along the way but in the end it work out beautifully and everyone\'s job got a whole lot easier. The program created parts that exceeded quality and productivity requirements. The program allowed for the casting department to reduce its most expense ingredient by 50% and allowed for the development of new more cost effective products. The program continued to evolve over the years and is still used today to manufacturer the majority of the metal parts created by the manufacturer. All information regarding this program is well documented in a web based manual that resides on each of the robots.</p>';

echo '</div>';
?>
